services:
  # Backend API Service
  - type: web
    name: investors-daily-brief
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FMP_API_KEY
        sync: false
      - key: BRAVE_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: FRED_API_KEY
        sync: false
      - key: PORT
        value: 5000
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: investors-daily-brief-frontend
    env: static
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production